version: '3'
services:
  postgres:
    container_name: app-postgres
    image: arm64v8/postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./local/pg:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./local/prometheus:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

#  api-server:
#    build:
#      context: .
#      dockerfile: ./api-server/Dockerfile
#    ports:
#      - "8081:8081"
#    environment:
#      - GO_ENV=development
#
#  worker-due-job-checker:
#    build:
#      context: .
#      dockerfile: ./worker-due-job-checker/Dockerfile
#    environment:
#      - GO_ENV=development
#    depends_on:
#      - pushgateway
#
#  worker-job-fixer:
#    build:
#      context: .
#      dockerfile: ./worker-job-fixer/Dockerfile
#    environment:
#      - GO_ENV=development
#    depends_on:
#      - pushgateway
